import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import { cookies } from "next/headers";
import { decodeJwt } from "./_utility/jwt";

// CTRL + SHIFT + P -> typescript version

// Font variables
const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

// Data about app
export const metadata: Metadata = {
  title: "Annas Next.js App",
  description: "Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const cookieStore = await cookies();
  const token = cookieStore.get("authToken")?.value;
  const user = token ? decodeJwt(token) : null;
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <section className=" min-h-screen flex flex-col">
          {/* Navbar */}
          <nav className=" flex justify-center p-4">
            <h1>Hello {user?.sub ?? "Guest"}</h1>
          </nav>
          <div className=" bg-gray-900 flex-1">{children}</div>
          {/* Footer */}
          <footer className=" p-4 flex justify-center">
            <p>Copyrights</p>
          </footer>
        </section>
      </body>
    </html>
  );
}
